::: {style="text-align: justify"}
## 2. Perspectivas sobre la violencia

El término violencia, es usado para describir fenómenos y conductas tanto individuales como colectivas, por lo que resulta especialmente difícil de definir y estudiar (Wieviorka, 2010). Respecto a que es la violencia, Bufacchi (2005), delimita las definiciones del concepto a dos enfoques: 1. una aproximación minimalista, que acota el término a la aplicación intencional de fuerza física, y 2. Una aproximación extensiva, que define la violencia como acto de violación de derechos. Una definición extensiva de la violencia más allá del uso de fuerza física, implica la transgresión de un límite, no obstante, la literatura es laxa respecto a definir qué es lo transgredido. Aunque permite observar otras formas de violencia, como simbólica o estructural, la falta de claridad conceptual conlleva la yuxtaposición de distintos planos de análisis en una situación victima-victimario.

Si bien fuerza y violencia no pueden ser entendidos como sinónimos, un acto violento sugiere el uso deliberado de la fuerza para dañar. Definir la violencia en estos términos, tiene la ventaja de establecer un límite claro respecto a lo que es un acto de violencia, evitando la tendencia a usar el término en otras situaciones de conflicto (Bufacchi, 2005). Debido a su claridad conceptual respecto a que es la violencia, utilizaremos una definición minimalista de violencia.

En cuanto a cómo se origina la violencia, en todas las corrientes existe una tensión entre el sujeto y la estructura, o bien entre lo individual y lo colectivo, en relación a las causas y el surgimiento del fenómeno. Arteaga (2003), sitúa el espacio de la violencia en base a los conceptos de diferencia y distancia. Aunque no explican la aparición del fenómeno, la idea de diferencia permite analizar la relación entre perpetrador y víctima en base a la aparición de un otro diferente. Por otro lado, la distancia social, definido como el grado y calidad de entendimiento que caracterizan las relaciones sociales, permite dibujar una frontera simbólica en donde se ejerce la violencia (Arteaga, 2003). El aumento de la distancia permite trazar espacios de inclusión o exclusión respecto a quienes y por qué se ejerce la violencia. En este espacio, el observador construye la justificación (o rechazo) del acto violento y la relación entre perpetrador y víctima.

### 2.1 Justificaciones de la violencia en contexto de protesta

La literatura distingue las justificaciones de la violencia en contexto de protesta según quienes la ejecutan y cuál es su objetivo. Por un lado, la violencia ejercida por Carabineros, denominada violencia por el control social, y por otro, la violencia empleada por los manifestantes, llamada violencia por el cambio social (Gerber et al., 2017).

Para abarcar las diferencias en las justificaciones del uso de la violencia policial, se puede distinguir esta según sus objetivos: entre violencia policial como control social y violencia policial como castigo (Gerber, Puga, et al., 2021). Mientras que el uso razonable de la fuerza, proporcional a la seriedad de la amenaza, y usando el mínimo de fuerza necesario, tiene por objetivo el control social, cuando el uso de la fuerza excede la seriedad de la amenaza y el mínimo de fuerza necesario, su objetivo no es solo controlar, sino que corresponde a una forma de castigo social.

Aunque se pueden distinguir dos motivaciones para apoyar la violencia policial, nuestra propuesta de estudio se centrará en las percepciones de violencia más allá de su objetivo, pues en contexto de protesta social, ambas dimensiones expresan el apoyo al control del orden público por parte de la policía. Así, nos centraremos en la justificación de la violencia de Carabineros y la justificación de la violencia de manifestantes.

### 2.2 Determinantes de la justificación de la violencia en contexto de protesta

Estudios previos indican que la legitimidad policial (Worden & McLean, 2017) y la percepción de justicia procedimental (Tyler & Blader, 2003), predicen la aceptación pública al uso de la violencia policial. Cuando las autoridades realizan procedimientos justos y neutrales, las personas se sienten valoradas y son más propensas a acatar voluntariamente la autoridad policial (Gerber, Moya, et al., 2021). La legitimidad policial y la percepción de justicia procedimental, insta a los ciudadanos a aceptar el uso de la fuerza monopólica de la autoridad, pero solo cuando se mantiene dentro de ciertos límites normativos. La policía debe actuar de una forma procedimentalmente justa, pues actuar fuera de la ley eventualmente es una amenaza a su propia legitimidad (Bradford et al., 2017). La percepción de injusticia en el trato se relaciona con menor legitimidad de las autoridades, lo que lleva a una mayor justificación de la acción colectiva no normativa (Gerber et al., 2018).

Sin embargo, diversas investigaciones resaltan que la justicia procedimental y la legitimidad policial solo se relaciona con la justificación de la violencia por el control social. Cuando el uso de la fuerza policial es excesivo, es decir, cuando sobrepasa la seriedad de la amenaza y el uso mínimo de la fuerza necesaria (Gerber, Puga, et al., 2021), se necesita otro patrón de motivaciones, que está guiado por las creencias ideológicas de una persona acerca del orden social (Gerber & Jackson, 2016).
La justificación de la violencia de manifestantes ha sido relacionada con la identificación con manifestantes, la eficacia percibida del uso de tácticas violentas, emociones negativas hacia Carabineros y emociones positivas hacia manifestantes de primera línea. Específicamente, la identificación con manifestantes actúa como mediador sobre la justificación de tácticas violentas en la protesta (Valeria-Zambrano, 2023).

Así también, la justificación de la violencia en contexto de protesta ha sido relacionada con las teorías de justicia distributiva en Chile (Venegas, 2022) Quienes perciben menor injusticia en la distribución de los ingresos de los obreros, más justifican la violencia policial de Carabineros en situaciones como usar la fuerza para desalojar liceos tomados o reprimir marchas pacíficas. No obstante, el efecto del sentido de injusticia del obrero en la justificación de reprimir marchas pacíficas, pierde relevancia al incluir el efecto de ideologías autoritarias y de dominancia social. Por otra parte, quienes consideran que los gerentes están injustamente recompensados justifican más la violencia por el cambio social (Venegas, 2022).

### 2.3 Ideología

Aunque de larga data, el continuo izquierda-derecha se sigue utilizando para diferenciar posturas ideológicas en base a un criterio básico: su posición respecto a la igualdad (Bobbio, 1997). Para la derecha política, la desigualdad entre individuos se acepta al considerarla natural, valorando las tradiciones y costumbres. En cambio, la izquierda política considera la desigualdad como una característica social, favoreciendo políticas en torno a la igualdad. Como parte de un continuo con posiciones intermedias, denominadas como centro político, Bobbio (1997), distingue los extremos en base a su posición con la libertad. Mientras que las posiciones moderadas, difieren respecto al problema de la igualdad, aceptan las reglas de la democracia. Jost (2021), presenta una conceptualización similar, advirtiendo dos ejes que separan la izquierda y la derecha política. 1. advocar o resistir el cambio social y 2. aceptar o rechazar la desigualdad social, económica y política.

La vigencia del continuo izquierda-derecha como indicador de la ideología política ha sido ampliamente discutido por la literatura especializada (Haye et al., 2009). En este sentido, la orientación política también ha sido ligada a la justificación de la violencia en contexto de protesta en diversos contextos, incluyendo el contexto latinoamericano (Rottenbacher, 2012).

En concordancia con las ideas que distinguen izquierda y derecha, las personas de izquierda apoyan las reivindicaciones sociales, por lo que justifican menos la violencia de Carabineros. En cambio, quienes se identifican con la derecha, apoyan fuertemente la violencia de Carabineros (Godoy et al., 2024). Otros estudios añaden factores relacionados a la orientación política en su ordenamiento entre izquierda y derecha, como la confianza en la policía, el apoyo a manifestaciones y percepción de respeto a los derechos humanos(Ross & Navia, 2024).

### 2.4 Emociones

El rol de las emociones en las percepciones sociales ha sido ampliamente estudiado desde la sociología. Diversos autores hablan de un giro afectivo, buscando vincular las emociones humanas con los problemas fundamentales de la sociología (Martell & Caro, 2023). Aunque las emociones actúan en diversos planos relacionados entre sí, estudiar este fenómeno desde la sociología implica delimitar cual es el componente propiamente social de estas. Aún cuando se entienden las emociones como un fenómeno relacional entre cultura y biología, la sociología ha optado por una salida constructivista en cuanto las emociones son objetos cognocibles en la medida en que estas se comunican (Bericat, 2000).

Desarrollos teóricos posteriores han resaltado la relevancia de las emociones que experimentan los individuos en relación a un grupo social. En este caso, la dimensión social de las emociones reside en que, bajo ciertas características, las personas pueden conectar entre sí incluso si son observadores de una acción que es perpetrada por una tercera persona (Yzerbyt et al., 2003).
La teoría de las emociones intergrupales, destaca el rol de estas en la regulación de las percepciones y la conducta de los individuos, incluyendo las relaciones intra e intergrupales (Mackie et al., 2000). Respecto a las relaciones intergrupales, el rol de las emociones reside en el reconocimiento de la identidad del sujeto en su relación con el grupo y la evaluación que se realiza del contexto (Yzerbyt et al., 2003). La premisa de esta teoría resalta el aspecto cognitivo, en donde las respuestas emocionales diferenciadas frente al mismo estímulo obedecen a mecanismos de cognición diferenciados (Smith et al., 2007).

Aunque hay poca evidencia respecto a como las emociones moldean las justificaciones de la violencia, una de las áreas temáticas de la sociología de las emociones ha sido la conexión entre movilizaciones sociales y sentimientos (Ariza, 2021). En este sentido, se ha resaltado el rol del miedo como emoción social, en cuanto representa la fragilización de los vínculos sociales. Así también, en una situación de protesta social, diversas percepciones y actitudes pueden verse afectadas por emociones específicas relacionadas al contexto y los actores involucrados (Jasper, 1998).

La influencia del miedo sobre otros fenómenos ha sido ampliamente estudiado en el ámbito de la criminología. Algunos autores (Vozmediano, 2008), sugieren separar la percepción subjetiva de los individuos de los índices objetivos de seguridad y delito. Esto implica entender el miedo a la delincuencia más allá de una perspectiva criminológica, como parte de una temática mayor de la percepción de inseguridad (Muratori & Zubieta, 2013), que incluye no solo la delincuencia tradicional sino también el vandalismo, el terrorismo, u otras amenazas, en las que se puede incluir las protestas sociales.

### 2.5 Relación entre ideología y emociones

Desde la psicología social se han reelaborado las diferencias entre izquierda y derecha, proponiendo una perspectiva de la ideología como fenómeno motivado cognitivamente. El concepto ha sido definido brevemente por Erikson & Tedin (2003; en Jost et al., 2008) como un conjunto de creencias sobre el orden social y como este debe ser alcanzado. Las teorías de justificación sistémica (Jost et al., 2004), han utilizado críticamente el concepto como la manera en que mitos legitimadores consensuados contribuyen a la estabilidad de jerarquías y desigualdades sociales entre grupos (Jost, Nosek, et al., 2008).

Una perspectiva de la ideología como fenómeno motivado cognitivamente pone especial énfasis en cómo esta refuerza necesidades o motivaciones de tipo epistémico, relacional y existencial (Jost, Ledgerwood, et al., 2008), que actúan como patrones de conducta alineando actitudes, creencias y preferencias de las personas con estas necesidades. Los motivos epistémicos están relacionados a la necesidad de orden, reducir incertidumbre, complejidad o ambigüedad, la búsqueda de seguridad y orden en la vida. Las motivaciones relacionales refieren al deseo de establecer relaciones interpersonales e identificarse socialmente. Finalmente, las motivaciones existenciales, que apuntan a la necesidad por manejar circunstancias amenazadoras y a la búsqueda de seguridad y sentido (Jost et al., 2003).

Si la ideología es un conjunto de actitudes, valores y creencias, junto con motivaciones existenciales, epistémicas y relacionales, puede ser separada por su contenido discursivo y por su función, en cuanto las necesidades psicológicas y sociales que satisface. La relación entre contenido ideológico y función psicológica, se ordenaría como un proceso de afinidad lectiva, en donde los discursos ideológicos son seleccionados y reinterpretados en base a las motivaciones psicológicas de los individuos (Jost et al., 2017).
La literatura advierte una relación entre la percepción del miedo como motivación existencial y el conservadurismo político de derecha (Jost et al., 2017). Una serie de estudios relacionan el apoyo a actitudes conservadoras con necesidades epistémicas y relacionales como la percepción de miedo, amenaza, intolerancia a la ambigüedad, evitar la incertidumbre y la necesidad de orden (Thórisdóttir & Jost, 2011).

Aunque el tratamiento de las emociones desde las perspectivas de la afinidad lectiva (Jost, Nosek, et al., 2008) y de las emociones intergrupales (Smith et al., 2007) incurren en cierto esencialismo psicológico (Estrada et al., 2007), en la medida en que se destacan las formas de percepción individual en las representaciones sociales, estos argumentos pueden ser extendido más allá de este plano, destacando el aspecto social o intergrupal de las emociones y sus efectos en las percepciones de los individuos.
En este sentido, puede vincularse las emociones a distintos fenómenos relacionado con las percepciones sociales: ¿hasta qué punto el miedo tiene un efecto directo o indirecto en las relaciones intergrupales?, ¿cómo se relacionan las emociones con categorizaciones racionales como la orientación política.

### 2.6 Otros determinantes

La literatura especializada también menciona otros determinantes socio-demográficos de la justificación de la violencia en contexto de protesta. Los hallazgos más consistentes indican que los grupos minoritarios son más críticos hacia el uso de la violencia policial que los grupos mayoritarios (Arthur & Case, 1994). En Chile, por ejemplo, se ha observado que las personas pertenecientes a grupos indígenas tienden a justificar menos la violencia de Carabineros (Gerber et al., 2018).
Además, diversas investigaciones sugieren que el sexo influye en la justificación al uso de la violencia en contexto de protesta. En general los hombres justifican más el uso de la fuerza policial, así como personas adultas por sobre jóvenes (Gerber, Puga, et al., 2021).

Por último, en el contexto chileno, el nivel educacional se ha identificado como un factor relevante en la justificación de la violencia en contexto de protesta. A mayor nivel educativo, menor justificación de la violencia tanto de Carabineros como de manifestantes (Godoy et al., 2024).

### 2.7 El caso chileno
Las agudas manifestaciones que sucedieron el 18 de octubre de 2019 se extendieron por más de cinco meses, y se detuvieron definitivamente con la llegada de la pandemia de Covid-19 que comenzó en marzo de 2020. Durante este periodo, las protestas iniciadas por estudiantes secundarios mostraron un amplio repertorio de acciones: las evasiones masivas en el metro de Santiago se transformaron en manifestaciones callejeras interrumpiendo el tránsito, barricadas y marchas no autorizadas por todo el país. La manifestación pacífica, daba paso a formas más violentas de protestas: incendios, daño al mobiliario público, saqueos a locales comerciales y enfrentamientos con Carabineros.

Desde el día 18 de octubre y durante diez días, el ex presidente Sebastián Piñera declara estado de excepción, habilitando el accionar de las fuerzas armadas en el control del orden público y decretando toque de queda. En este contexto, el debate sobre la protesta social y el accionar de Carabineros en la contención del orden público se polariza. Por un lado, el estallido delincuencial denunciado por el gobierno, frente a un “enemigo poderoso”1 es seguido de iniciativas de ley “anti-barricadas” y “anti-encapuchados”, buscando aumentar las penas para quienes cometan estos delitos. Por otra parte, un sector de la población defiende el actuar de los llamados encapuchados, presentes en marchas y movilizaciones anteriores, que pasan a ser nombrados como manifestantes de primera línea, argumentando su actuar frente a la represión de Carabineros.

Frente a la masividad de las protestas, diversas instituciones, tanto nacionales como internacionales, cuestionaron el rol de Carabineros frente al control del orden público, argumentando una política deliberada para dañar manifestantes dada por los mandos de Carabineros (Amnistía Internacional, 2020) y un uso excesivo de la fuerza (INDH, 2020), poniendo en tela de juicio los métodos y la discrecionalidad de la institución respecto al control del orden público, el uso de armas no letales o menos letales como la escopeta antidisturbios, gases lacrimógenos y la acción de las fuerzas de orden público frente a la congregación de marchas pacíficas.
Aunque organismos internacionales como Human Right Watch (2019) y la Comisión Interamericana de Derechos Humanos (2020) dieron cuenta de violaciones a los Derechos Humanos por parte de Carabineros en el marco del llamado estallido social, incluyendo el derecho a la vida y el derecho a reunirse pacíficamente, el debate fue controvertido, generando opiniones favorables hacia el actuar de Carabineros frente al denunciado estallido delincuencial, apoyando la legítima aspiración de la institución por controlar el orden público.


El ex candidato presidencial José Antonio Kast llegó a declarar que las violaciones masivas a los derechos humanos por parte de Carabineros no existieron, denunciando la violencia y la alteración del orden público como una estrategia sostenida por sectores de izquierda (Durán & Rojas, 2021). Sus dichos dejan entrever la opinión de un sector de la población que se identificó fuertemente con la institución policial, avalando sus acciones e invocando la necesidad de orden público frente a la radicalización de la protesta durante el estallido social, haciendo referencia a una mayoría silenciosa que buscaba la paz y la recuperación del orden público.
El debate sobre el control del orden público por parte de Carabineros queda planteado, mas no resuelto: ¿hasta qué punto puede Carabineros intervenir por el control del orden público sin menoscabar el derecho a la reunión pacífica? Aunque la discusión se enfría luego de la pandemia de Covid-19 (Nava & Grigera, 2022), dando paso a una agenda marcada principalmente por: 1. Una recesión económica con una tasa de inflación superior al 10% durante 2022 (García, 2022), y 2. Una crisis de seguridad pública, marcada por tres factores: el incremento de la presión migratoria post Covid, el aumento de la delincuencia y los atentados en la Araucanía producto del conflicto mapuche (Heiss, 2023). Esta crisis de seguridad es uno de los elementos más resaltados en la opinión pública (CEP, 2023), lo que se ha reflejado en un mayor apoyo a Carabineros en el combate contra la delincuencia (CADEM, 2023).

Rottenbacher (2008, p. 37), define el contexto socio-emocional como las representaciones colectivas de la situación sociopolítica de una nación, cargadas afectivamente, que predominan en una colectividad durante un período histórico y sociopolítico determinado. Estas representaciones influyen en las relaciones sociales dentro de esa colectividad y en sus representaciones sociales sobre el mundo, el presente y el futuro. Diversas investigaciones, incluso en el contexto latinoamericano (Rottenbacher de Rojas, Amaya , Genna, & Pulache, 2009), sugieren que la percepción de inseguridad incrementa más en quienes son renuentes a los cambios sociales. Las actitudes hacia el crimen, vigilancia y punitivismo expresan un mismo fenómeno emergente: están envueltos en lo que los individuos perciben como hostil, lo que quieren y como creen que debe organizarse la sociedad (Gerber & Jackson, 2016, p. 15).


:::
