::: {style="text-align: justify"}


## 8. Conclusiones

De forma general, la evidencia recogida permite indicar que: 1. La orientación política tiene un efecto estadísticamente significativo en la justificación de la violencia de Carabineros y manifestantes, aun después de controlar por las variables seleccionadas. Este efecto, sigue una lógica consistente con el continuo izquierda-derecha. 2. El miedo a manifestantes violentos tiene un efecto positivo y estadísticamente significativo sobre la justificación de la violencia de Carabineros, controlando por orientación política y las variables sociodemográficas seleccionadas, no obstante, el miedo a Carabineros no es estadísticamente significativo en la justificación de la violencia de manifestantes. 3. Personas de izquierda y derecha sienten más miedo por manifestantes violentos que por el accionar de Carabineros en las manifestaciones, sin embargo, las diferencias entre los puntajes sugieren que existe una percepción diferenciada según orientación política. 4. Aunque el miedo a los actores relacionados a la protesta social altera parcialmente la magnitud de la relación entre orientación política y la justificación de la violencia, la interacción entre miedo y orientación política no es estadísticamente significativa. 5. El nivel educativo resulta estadísticamente significativo para explicar las justificaciones de la violencia. Esquemáticamente, podemos indicar que, a mayor nivel educativo, menos se justifica la violencia de manifestantes, mientras que un nivel educativo de primaria y secundaria baja aumenta la probabilidad de justificar la violencia de Carabineros.

Las limitaciones de este estudio guardan relación principalmente con la medición de las variables observadas. Aunque la inspiración teórica de este estudio es que la justificación de la violencia, la orientación política y el miedo a los actores relacionados con la protesta se pueden medir directamente, las variables dependientes hacen referencia a contextos diferentes, respecto a estudiantes tirando piedras a Carabineros, o sobre el uso de la fuerza de Carabineros en las marchas. El hecho de acotar la pregunta a las movilizaciones estudiantiles, o hacer referencia respecto al uso de la fuerza, en vez de reprimir o violencia puede cambiar que entienen los encuestados respecto a la situación planteada. Lo que se deduce, es que los encuestados rellenan este contexto general en base a sus propias creencias (Molden, 2014), dando luces sobre sus actitudes hacia distintos grupos sociales.

También, los conceptos de miedo a Carabineros y miedo a manifestantes, fueron medidos con la siguiente pregunta: ¿En qué medida le generan miedo los siguientes actores y situaciones referidos a las protestas iniciadas a mediados de Octubre? 1. Los manifestantes violentos en las protestas. 2. El accionar de las fuerzas de seguridad pública en las manifestaciones. Mientras que el miedo a manifestantes incluye en su pregunta una referencia textual a los manifestantes y a la violencia, la pregunta relacionada con el miedo a Carabineros es más difusa, al indicar las fuerzas de seguridad pública, relacionadas con las comisarías de fuerzas especiales y control del orden público, más que a la institución completa, relacionado con Carabineros en otras funciones.

Finalmente, también hay limitaciones respecto a la validez de la orientación política como proxy de la ideología política. Reducir la ideología al continuo izquierda-derecha presenta la dificultad de como situar las actitudes de quienes se identifican como centro o apolíticos. Para evitar una sobre simplificación de la ideología política, desde la psicología social se ha optado usar dos escalas que configuran un plano más complejo (Duckitt & Sibley, 2009), denominadas Right Wing Authoritarianism (Altemeyer, 2004), y Social Dominance Orientation (Ho et al., 2012). Sin embargo, diversos estudios han confirmado la relación entre estas escalas con el conservadurismo político de derecha (Jost, 2021), defendiendo así la vigencia del continuo izquierda-derecha como proxy de la ideología política (Rottenbacher, 2012; Haye et al., 2009).

Estas limitaciones pueden ser tomadas como proyecciones para futuras investigaciones respecto a dos elementos: 1. La medición de las variables. 2. Las técnicas estadísticas utilizadas. Las justificaciones de la violencia son un problema complejo, que involucra diversos planos de la sociedad, y que puede ser abordado desde distintas perspectivas. Estas justificaciones pueden estar relacionadas entre sí, mostrando un escenario más complejo respecto a donde y cuando se permite la violencia. En este sentido, se puede avanzar hacia mediciones más complejas, que aprehendan la complejidad de la relación entre diversas formas de justificación de la violencia.

Respecto a la orientación política, se puede proyectar el uso de las escalas de Right Wing Authoritarianism, y Social Dominance Orientation, lo que permitiría situar de mejor manera las categorías centro y apolítico en el continuo izquierda-derecha. Estas escalas también pueden dar mayor claridad respecto a la relación entre el miedo a los actores relacionados con la protesta social y la ideología política. A su vez, la medición del miedo puede realizarse a través de escalas más complejas que involucren otras emociones y otros grupos sociales, mostrando un panorama de dinámicas sociales más complejas en distintos escenarios de conflicto intergrupal.

Finalmente, la relación entre justificación de la violencia, orientación política y el miedo a los actores relacionados con la protesta social también puede estudiarse a través de modelos longitudinales, vinculando en una lógica temporal el miedo como emoción primaria, la orientación política como categorización racional y la justificación de la violencia, como actitud social moldeada por estos elementos.

:::
