::: {style="text-align: justify"}

## 7. Discusión

En la historia política reciente de Chile, la relación entre Carabineros y ciudadanía ha estado marcada por bajos niveles de legitimidad y desconfianza con la policía uniformada. A su vez, los efectos del estallido social, han puesto en el debate público cual es rol de Carabineros en el control del orden público, así como cuáles son sus facultades respecto a esta labor. Desde la literatura especializada, se ha planteado la importancia de que la policía respete los procedimientos establecidos para mantener su legitimidad (Gerber et al., 2018).

Sin embargo, en una situación de violencia intergrupal, como es el caso de los enfrentamientos entre Carabineros y manifestantes en contexto de protesta, el procedimiento del uso de la fuerza resulta poco claro a los ojos de un observador ¿Qué nivel de violencia se justifica? ¿Cuándo se justifica?, una parte de la literatura plantea que más allá de los procedimientos y la legitimidad, la respuesta a estas preguntas puede ser ideológica por naturaleza (Gerber & Jackson, 2016). En base a esta idea, se planteó la necesidad de esclarecer la relación entre la orientación política, como indicador resumido de la ideología política, y las justificaciones de la violencia.

Así también, el resurgimiento esporádico del conflicto entre Carabineros y manifestantes demuestran lo frágil y complejas que son las interacciones entre la ciudadanía y la policía uniformada en nuestro país. En este contexto de violencia intergrupal, el miedo como emoción social puede tener un rol en el reconocimiento de la identidad del sujeto en su relación con el grupo y la evaluación que se realiza del contexto (Yzerbyt et al., 2003). Así, entre identidad y reconocimiento, se dibujan espacio de inclusión y exclusión respecto hacia quienes y por qué se justifica la violencia.

En este espacio teórico, es que se buscó responder de qué forma se relaciona la orientación política con el miedo a los actores relacionados a la protesta social en la justificación de la violencia en contexto de protesta en Chile el año 2022.

Así, se plantearon cinco hipótesis distintas: 1. individuos de orientación política de derecha, tienen mayor probabilidad de justificar la violencia policial, mientras que individuos de orientación política de izquierda, tienen mayor probabilidad de justificar la violencia de manifestantes. 2. individuos que indiquen mayor miedo a manifestantes, tienen mayor probabilidad de justificar la violencia de Carabineros, mientras que individuos que indiquen mayor miedo a Carabineros, tienen mayor probabilidad de justificar la violencia de manifestantes. 3. hay una percepción diferenciada del miedo a los actores relacionados con la protesta social según orientación política. Personas de derecha sienten más miedo por los manifestantes, mientras que personas de izquierda sienten más miedo a Carabineros. 4. existe un efecto interactivo entre orientación política de derecha y el miedo a manifestantes, aumentando la probabilidad de justificar la violencia policial. 5. existe un efecto interactivo entre orientación política de izquierda y el miedo a Carabineros, aumentando la probabilidad de justificar la violencia de manifestantes.

Respecto a la hipótesis 1, se puede advertir que existe evidencia suficiente para confirmarla, en cuanto la orientación política de derecha tiene un efecto positivo y estadísticamente significativo en la justificación de la violencia de Carabineros, aun después de controlar por miedo a manifestantes violentos y las variables sociodemográficas seleccionadas. Para el modelo 3, los encuestados de centro tienen un 35% más de probabilidad de justificar esta forma de violencia en contraste con quienes se identifican de izquierda (OR: 1.35, p < 0.05), mientras que los encuestados de derecha tienen un 58% más de justificar la violencia de Carabineros en comparación a los encuestados de izquierda.

Así también, hay una relación estadísticamente significativa y positiva entre la orientación política de izquierda y la justificación de la violencia de manifestantes, controlando por miedo a Carabineros y las variables sociodemográficas de interés. Para el modelo 3, los encuestados de centro tienen un 44% menos de probabilidad de justificar la violencia de manifestantes en comparación con quienes se identifican de izquierda (OR: 0.56, p < 0.001), mientras que encuestados de derecha tienen un 49% menos de probabilidad de justificar la violencia de manifestantes respecto a encuestados de izquierda (OR: 0.51, p < 0.001). Así también, los encuestados apolíticos tienen un 47% menos probabilidad de justificar esta forma de violencia respecto a quienes se identifican de izquierda (OR: 0.53, p < 0.001).

Estos hallazgos indican que la justificación de la violencia de manifestantes es una percepción política relacionado con la izquierda, acercando las categorías de centro y apolítico a las percepciones de la derecha política, mientras que la justificación de la violencia de Carabineros se relaciona con el centro y la derecha política.

Respecto a la conexión entre miedo a los actores relacionados con la protesta social y justificación de la violencia, existe evidencia parcial para la hipótesis 2. Por un lado, el miedo a manifestantes tiene una relación positiva y significativa en la justificación de la violencia de Carabineros, aún después de controlar por orientación política y variables sociodemográficas. Para el modelo 3, quienes indican sentir poco miedo a manifestantes violentos tienen un 124% más de probabilidad de justificar la violencia de Carabineros en comparación con quienes indican sentir nada de miedo a manifestantes violentos, mientras que quienes sienten mucho miedo a manifestantes violentos, tienen un 98% más de probabilidad de justificar esta forma de violencia respecto a quienes sienten nada de miedo a manifestantes violentos. Por otra parte, el efecto del miedo a Carabineros no es estadísticamente significativo en la justificación de la violencia de manifestantes.

Respecto a la hipótesis 3, que plantea una percepción diferenciada del miedo a los actores relacionados con la protesta social según orientación política, los resultados obtenidos muestran evidencia parcial, pues personas de izquierda y derecha sienten más miedo por manifestantes violentos que por el accionar de Carabineros en las manifestaciones. Sin embargo, aunque el promedio de miedo a manifestantes violentos es mayor que el promedio de miedo a Carabineros para todas las orientaciones políticas, si existe una percepción diferenciada en la medida en que la diferencia entre estos promedios es importante. Por ejemplo, el promedio de miedo a manifestantes en los encuestados de derecha es de 4.21, frente a 3.8 para los encuestados de izquierda. También, el promedio de miedo al accionar de Carabineros es de 2.72 para los encuestados derecha y de 3.8 para quienes se identifican con la izquierda.

En segundo lugar, en el continuo izquierda-derecha es necesario ubicar a quienes se identifican como de centro o apolíticos, en cuanto estas categorías representan un espacio para quienes presentan menores niveles de politización. Respecto a estos grupos, podemos indicar dos alternativas: 1. Tendencias mixtas; 2. Preferencias autoritarias. Los hallazgos en el marco de esta investigación no permiten decantar por ninguna de las dos opciones, no obstante, respecto a la justificación de la violencia, los promedios de estos grupos son comparables a los encuestados de derecha, pero con niveles más altos de miedo tanto hacia Carabineros como hacia manifestantes violentos.

La evidencia recopilada también permite rechazar las hipótesis 4 y 5, En cuanto el efecto de interacción entre orientación política de derecha y miedo a manifestantes violentos no es estadísticamente significativo en la justificación de la violencia de Carabineros, como tampoco lo es la interacción entre orientación política de izquierda y miedo a Carabineros en la justificación de la violencia de manifestantes. Aunque se puede argumentar que el miedo a los actores relacionados con la protesta social actúa como variable moderadora (Ato & Vallejo, 2010), alterando la magnitud de la relación entre orientación política y la justificación de la violencia, esta moderación es parcial y no toma forma de una interacción.

Así también, las variables de control entregan información valiosa respecto a los grupos que justifican los dos tipos de violencia estudiados. El nivel educativo resultó ser especialmente significativo en la justificación de la violencia de manifestantes. Un nivel educativo de primaria y secundaria básica, o un nivel de secundaria alta, disminuye en un 37% la probabilidad de justificar esta forma de violencia respecto a los encuestados con un nivel de primaria incompleta. Así también, un nivel educativo terciario o de postgrado disminuye en un 50 % la probabilidad de justificar la violencia de manifestantes respecto a quienes tienen un nivel de primaria incompleta. También, para la justificación de la violencia de Carabineros, un nivel educativo de primaria y secundaria baja aumenta en un 46% la probabilidad de justificar esta forma de violencia en comparación a quienes tienen un nivel de primaria incompleta.

La edad resultó ser significativa respecto a ambas formas de violencia. Por un lado, a mayor edad, la probabilidad de justificar la violencia de Carabineros aumenta en un 1%, mientras que, para la justificación de la violencia de manifestantes, a medida en que aumenta la edad, la probabilidad disminuye en un 2%. Finalmente, cabe mencionar que a diferencia de estudios anteriores (Gerber et al., 2018), la pertenencia a un grupo indígena no resultó ser significativo estadísticamente para la justificación de la violencia de Carabineros o manifestantes.

Aunque existen diversos estudios previos sobre justificación de la violencia en contexto de protesta (Rottenbacher & Schmitz, 2013; Gerber et al., 2022; Venegas, 2022), buscamos aportar con una perspectiva novedosa al integrar el miedo y la orientación política como determinantes. De forma general, los hallazgos presentados suman evidencia respecto a la naturaleza ideológica de la justificación de la violencia, así también, abre espacios de investigación respecto al rol de las emociones en las justificaciones de la violencia.

En este sentido, los hallazgos recogidos permiten contribuir a la literatura especializada en tres aspectos distintos: en primer lugar, aporta nueva evidencia respecto a la forma que influye la orientación política en la justificación de la violencia en contexto de protesta. Solo la orientación política de izquierda se asocia a una mayor justificación de la violencia de manifestantes, mientras que ser de centro o de derecha se asocia a una mayor justificación de la violencia de Carabineros.

En segundo lugar, aporta a la comprensión del miedo a los actores relacionados con la protesta social. Respecto a ello, la información proporcionada indica que el miedo al accionar de Carabineros en las manifestaciones no influye en la justificación de la violencia de manifestantes, no obstante, el miedo a manifestantes violentos si influencia la justificación de la violencia de Carabineros. Esto puede interpretarse como un signo de legitimidad policial, en la medida en que el miedo hacia este grupo no significa una justificación de la violencia a manifestantes.

En tercer lugar, los hallazgos recogidos en esta investigación resaltan el rol del nivel educativo como uno de los factores individuales que más afecta la justificación de ambas formas de violencia estudiadas. Respecto a la justificación de la violencia de Carabineros, un nivel educativo de primaria y secundaria baja aumenta la probabilidad de justificar esta forma de violencia en comparación a los encuestados con primaria incompleta. Para el caso de la justificación de la violencia de manifestantes, un nivel educativo de primaria y secundaria básica, o un nivel de secundaria alta, disminuye en un 37% la probabilidad de justificar esta forma de violencia respecto a los encuestados con un nivel de primaria incompleta. Así también, un nivel educativo terciario o de postgrado disminuye en un 50 % la probabilidad de justificar la violencia de manifestantes respecto a quienes tienen un nivel de primaria incompleta.

:::