::: {style="text-align: justify"}
## 1. Introducción

Las reflexiones sobre la violencia han estado en el centro del pensamiento moderno, pasando por argumentaciones contractualistas en donde se cede el ejercicio de la violencia al Estado, o entendiendo el carácter monopólico y legítimo del uso de la fuerza como propiedad fundamental del Estado moderno en Weber (Trovero, 2021). En cuanto experiencia humana, la violencia resurge de diversas formas y en distintos niveles. Por ende, evitar su propagación ha sido una preocupación fundamental de las sociedades democráticas.
Dentro de las fronteras del Estado, también resurgen situaciones de violencia doméstica, en donde algunos grupos se enfrentan por diversos motivos o razones. En la literatura sobre movimientos sociales, la aparición de esta forma de violencia es interpretada en un marco más amplio de política contenciosa, en donde ciertos actores hacen reclamos que afectan los intereses de otros actores, llevando a esfuerzos coordinados en nombre de estos intereses (Tilly y Tarrow, 2015 en Somma et al., 2024). En este contexto, las dinámicas de violencia intergrupal, es decir, aquella violencia que es conducida desde el interior de un grupo hacia el exterior (Gerber et al., 2018), se encuadran en la existencia de un conflicto entre fuerzas sociales que buscan cambiar o mantener determinado orden social (Godoy et al., 2024).

El caso chileno ofrece un contexto especial para vincular la relación entre Carabineros y ciudadanía con la literatura de movimientos sociales, pues a menudo las protestas se acompañan con hechos de violencia entre manifestantes y la fuerza policial. Sin embargo, el estallido social de 2019 superó con creces los parámetros de conflictividad observados con anterioridad en el país, en la medida en que el uso de tácticas violentas de protesta fue comparativamente elevado respecto a otros ciclos de protesta (Joignant et al., 2020).

Algunos estudios han destacado el rol que juega la percepción de desigualdad en el surgimiento de protestas sociales (Donoso & Von Bülow, 2017), de modo que es posible que exista una relación entre justificación de la violencia en contexto de protesta y percepción de la desigualdad social. De forma general, la justificación de la violencia se entiende como la argumentación que fundamenta una situación de violencia para desvincularlo de lo injusto, considerándolo como algo comprensible y con sentido (Basaure, 2020).

Una mayor percepción de desigualdad de ingresos es ligada con una mayor justificación de la violencia de manifestantes. Por el contrario, quienes indican menor percepción en la desigualdad de ingresos, justifican más la violencia de Carabineros (Godoy et al., 2024). También, la justificación de la violencia y la percepción de la desigualdad también han sido ligadas con las preferencias ideológicas de las personas. Para la derecha política, la desigualdad entre individuos se acepta al considerarla natural, valorando las tradiciones y costumbres. En cambio, la izquierda política considera la desigualdad como una característica social, favoreciendo políticas en torno a la igualdad (Bobbio, 1997).

Estudios en Chile indican que las personas de izquierda apoyan las reivindicaciones sociales, por lo que justifican menos la violencia de Carabineros. En cambio, quienes se identifican con la derecha, apoyan fuertemente la violencia de Carabineros (Godoy et al., 2024). También se indican otros factores, como el apoyo a las manifestaciones, la confianza en la policía, la percepción de respeto a los derechos humanos por parte de la fuerza policial como determinantes de la justificación de la violencia en contexto de protesta social (Ross & Navia, 2024).

Otro de los factores individuales que puede influir en las justificaciones de la violencia en contexto de protesta son las emociones. Las emociones se vinculan a distintos fenómenos relacionado con las percepciones sociales, entendidas estas como aquellos esquemas de conocimiento compartido acerca de la realidad social que orienta la conducta de las personas de un grupo social (Estrada et al., 2007).
8
Respecto a una situación de protesta social, diversas percepciones y actitudes pueden verse afectadas por emociones específicas relacionadas al contexto y los actores involucrados (Jasper, 1998). Específicamente, algunas investigaciones sugieren cierta afinidad entre la percepción del miedo y el conservadurismo político de derecha (Jost et al., 2017).

Considerando los aspectos específicos del caso chileno, el propósito de esta investigación es indagar en las relaciones entre la justificación de la violencia, orientación política y el miedo. Aunque ambos conceptos funcionan en planos distintos, son comparables en cuanto poseen cargas motivacionales que incitan a formas diferenciadas de acción. Tanto el miedo como la orientación política pueden ser factores relevantes para los individuos al evaluar normativamente una situación de violencia intergrupal. Con esto, se espera contribuir al entendimiento de como las emociones, particularmente el miedo, influye en la evaluación normativa de la violencia en contexto de protesta, en interacción con la orientación política.

En un escenario marcado por la polarización política y un aumento en la percepción de inseguridad y delincuencia (Gerber et al., 2024), el análisis de estos factores resulta especialmente pertinente para entender las dinámicas de legitimación de la violencia en el Chile post estallido social. Así, se espera aportar una perspectiva novedosa respecto a la compleja relación entre ciudadanía, manifestantes y fuerzas de orden en contexto de alta conflictividad social.

El razonamiento argumentativo de esta investigación parte desde el siguiente planteamiento: después de la pandemia de Covid-19, mientras estaba en marcha el proceso constituyente como respuesta al estallido social, una percepción creciente de inseguridad hizo que el combate a la delincuencia fuese el principal tema en la agenda pública (CEP, 2023).

Considerando este clima, el miedo como emoción intergrupal puede cobrar mayor relevancia en la justificación de la violencia en contexto de protesta. Así, proponemos que el miedo a los actores relacionados con la protesta social, actúa como variable moderadora, alterando la magnitud de la relación entre orientación política y justificación de la violencia en contexto de protesta social. Planteamos como pregunta de investigación: ¿Cómo se relaciona la orientación política con el miedo a los actores relacionados a la protesta social en la justificación de la violencia en contexto de protesta en Chile el año 2022?

Para responder la pregunta, se menciona brevemente algunas perspectivas teóricas sobre la violencia, se define que es la justificación de la violencia y cuáles son sus principales determinantes. Finalmente, se ahonda en los factores individuales, específicamente, el rol de la orientación política y el miedo. Asimismo, para indicar quienes justifican la violencia en contexto de protesta, se describe el escenario de auge y declive de las manifestaciones luego del estallido social.

En base a los objetivos e hipótesis de la investigación, se establece una estrategia metodológica mediante el uso de estadísticos univariados, bivariados, y finalmente se especifican las variables a utilizar para una serie de modelos de regresión logística ordinal con efectos de interacción (Agresti, 2018).



:::
