::: {style="text-align: justify"}
## 3. Marco Teórico

### 3.1 Perspectivas sobre la violencia

Cuando se estudia el uso de la fuerza por parte de la policía, se remite en esencia al carácter monopólico y legítimo de la fuerza por parte del Estado. Desde cierto momento hobbesiano en donde se cede el ejercicio de la violencia al Estado, o entendiendo el carácter monopólico y legítimo del uso de la fuerza como propiedad fundamental del Estado moderno en Weber (Trovero, 2020), la idea del Estado parece inseparable de la violencia, aunque no sea reducible a esta.

El término violencia, es usado para describir fenómenos y conductas tanto individuales como colectivas, por lo que resulta especialmente difícil de definir y estudiar (Wieviorka, 2009). Independiente de su relación con el concepto de Estado, las definiciones de la violencia son múltiples y provenientes desde distintas ciencias y corrientes teóricas. Respecto a que es la violencia, Bufacchi (2005), delimita las definiciones del concepto a dos enfoques: 1. una aproximación minimalista, que acota el término a la aplicación intencional de fuerza física, y 2. Una aproximación extensiva, que define la violencia como acto de violación de derechos.

Una definición extensiva de la violencia más allá del uso de fuerza física, implica la transgresión de un límite, no obstante, la literatura es laxa respecto a definir qué es lo transgredido. Aunque permite observar otras formas de violencia, como simbólica o estructural, la falta de claridad conceptual conlleva la yuxtaposición de distintos planos de análisis en una situación victima-victimario.

Aunque fuerza y violencia no pueden ser entendidos como sinónimos, un acto violento sugiere el uso deliberado de la fuerza para dañar. Definir la violencia en estos términos, tiene la ventaja de establecer un límite claro respecto a lo que es un acto de violencia, evitando la tendencia a usar el término en otras situaciones de conflicto (Bufacchi, 2005). Debido a su claridad conceptual respecto a que es la violencia, nos centraremos en esta definición.

En cuanto a como se explica la violencia, en todas las corrientes existe una tensión entre el sujeto y la estructura, o bien entre lo individual y lo colectivo, en relación a las causas y el surgimiento del fenómeno. Arteaga (2003), sitúa el espacio de la violencia en base a los conceptos de diferencia y distancia. Aunque no explican la aparición del fenómeno, la idea de diferencia permite analizar la relación entre perpetrador y víctima en base a la aparición de un otro diferente. Por otro lado, la distancia social, definido como el grado y calidad de entendimiento que caracterizan las relaciones sociales, permite dibujar una frontera simbólica en donde se ejerce la violencia (Arteaga, 2003). El aumento de la distancia permite trazar espacios de inclusión o exclusión respecto a quienes y por qué se ejerce la violencia. En este espacio, el observador construye la justificación (o rechazo) del acto violento y la relación entre perpetrador y víctima.

### 3.2 Justificaciones de la violencia en contexto de protesta

Como se mencionó anteriormente, la justificación de la violencia, se define como la argumentación que fundamente una situación de violencia para desvincularlo de lo injusto, considerándolo como algo comprensible y con sentido (Basaure, 2020). La literatura distingue las justificaciones de la violencia en contexto de protesta según quienes la ejecutan y cuál es su objetivo. Por un lado, la violencia ejercida por Carabineros (violencia por el control social), y por otro, la violencia empleada por los manifestantes (violencia por el cambio social) (Gerber, González, Jiménez-Moya, Moya, & Jackson, 2018).

Por otra parte, estudios previos indican que la legitimidad policial (Worden & McLean, 2017) y la percepción de justicia procedimental (Tyler & Blader, 2003), predicen la aceptación pública al uso de la violencia policial. Cuando las autoridades realizan procedimientos justos y neutrales, las personas se sienten valoradas y son más propensas a acatar voluntariamente la autoridad policial (Gerber, Figuereido, Sáez, & Orchard, 2023).

La legitimidad policial y la percepción de justicia procedimental, insta a los ciudadanos a aceptar el uso de la fuerza monopólica de la autoridad, pero solo cuando se mantiene dentro de ciertos límites normativos. La policía debe actuar de una forma procedimentalmente justa, pues actuar fuera de la ley eventualmente es una amenaza a su propia legitimidad (Bradford, Milani, & Jackson, 2016). La percepción de injusticia en el trato se relaciona con menor legitimidad de las autoridades, lo que lleva a una mayor justificación de la acción colectiva no normativa (Gerber, González, Jiménez-Moya, Moya, & Jackson, 2018).

Los hallazgos más consistentes indican que los grupos minoritarios son más críticos hacia el uso de la violencia policial que los grupos mayoritarios (Arthur & Case, 1994). Por ejemplo, en el caso de Chile, el efecto de la justicia procedimental es más fuerte en quienes se identifican como mapuches. Otras investigaciones, sugieren que factores sociodemográficos influyen en la justificación al uso de la violencia policial. En general los hombres justifican más el uso excesivo de la fuerza policial, así como personas con menor nivel educativo y personas adultas por sobre jóvenes (Gerber, y otros, 2021).

En virtud del estado de derecho, el estándar sobre el uso de la fuerza policial es normado por tres principios básicos que gozan de reconocimiento incontrovertido: el principio de necesidad, legalidad y proporcionalidad. El primero de ellos, implica que el uso de la fuerza debe contar con un fundamento jurídico suficiente, establecido previamente por el Estado, delimitando los parámetros del uso de la fuerza. El segundo de ellos, comprende tres obligaciones: usar medios no violentos cuando sea posible, bajo el único propósito de hacer cumplir la ley, y haciendo uso de la fuerza mínima necesaria que resulte razonable en las circunstancias existentes. Finalmente, el principio de proporcionalidad, que actúa como limitante frente al ejercicio de la fuerza, pues deben actuar según la gravedad del delito (Moral Araneda, 2021).

Este límite en el uso de la fuerza policial resulta difuso, especialmente para los observadores. Sin embargo, diversas investigaciones resaltan que cuando el uso de la fuerza policial es excesivo, es decir, cuando sobrepasa la seriedad de la amenaza y el uso mínimo de la fuerza necesaria (Gerber, y otros, 2021), se necesita otro patrón de motivaciones, que está guiado por las creencias ideológicas de una persona acerca del orden social (Gerber & Jackson, 2016).

Para abarcar las diferencias en las justificaciones del uso de la violencia policial, se puede distinguir esta según sus objetivos: entre violencia policial como control social y violencia policial como castigo (Gerber, y otros, 2021). Mientras que el uso razonable de la fuerza, proporcional a la seriedad de la amenaza, y usando el mínimo de fuerza necesario, tiene por objetivo el control social, cuando el uso de la fuerza excede la seriedad de la amenaza y el mínimo de fuerza necesario, su objetivo no es solo controlar, sino que corresponde a una forma de castigo social. Aunque se pueden distinguir dos objetivos distintos para apoyar la violencia policial, nuestra propuesta de estudio se centra en quienes ejecutan la violencia, más allá de sus motivaciones. Considerando que en las manifestaciones sociales existe una situación de violencia intergrupal entre Carabineros y manifestantes, nuestro interés es la justificación de la violencia policial y la justificación de la violencia de manifestantes.

### 3.3 Ideología y emociones

Aunque de larga data, el continuo izquierda-derecha se sigue utilizando para diferenciar posturas ideológicas en base a un criterio básico: su posición respecto a la igualdad (Bobbio, 1996). Para la derecha política, la desigualdad entre individuos se acepta al considerarla natural, valorando las tradiciones y costumbres. En cambio, la izquierda política considera la desigualdad como una característica social, favoreciendo políticas en torno a la igualdad. Como parte de un continuo con posiciones intermedias, denominadas como centro político, Bobbio (1996) distingue los extremos en base a su posición con la libertad. Mientras que las posiciones moderadas, difieren respecto al problema de la igualdad, aceptan las reglas de la democracia. Jost (2021), presenta una conceptualización similar, advirtiendo dos ejes que separan la izquierda y la derecha política. 1. advocar o resistir el cambio social y 2. aceptar o rechazar la desigualdad social, económica y política.

Desde la psicología social se han reelaborado esas diferencias, proponiendo una perspectiva de la ideología como fenómeno motivado cognitivamente. El concepto ha sido definido brevemente por Erikson & Tedin (2003; Jost, Federico, & Napier, 2009) como un conjunto de creencias sobre el orden social y como este debe ser alcanzado. Las teorías de justificación sistémica (Jost, Banaji, & Nosek, 2004), han utilizado críticamente el concepto como la manera en que mitos legitimadores consensuados contribuyen a la estabilidad de jerarquías y desigualdades sociales entre grupos (Jost, Nosek, & Gosling, 2008).

Una perspectiva de la ideología como fenómeno motivado cognitivamente pone especial énfasis en como esta refuerza necesidades o motivaciones de tipo epistémico, relacional y existencial (Jost, Ledgerwood, & Hardin, 2008), que actúan como patrones de conducta alineando actitudes, creencias y preferencias de las personas con estas necesidades. Los motivos epistémicos están relacionados a la necesidad de orden, reducir incertidumbre, complejidad o ambigüedad, la búsqueda de seguridad y orden en la vida. Las motivaciones relacionales refieren al deseo de establecer relaciones interpersonales e identificarse socialmente. Finalmente, las motivaciones existenciales, que apuntan a la necesidad por manejar circunstancias amenazadoras y a la búsqueda de seguridad y sentido (Jost, Glaser, Kruglanski, & Sulloway, 2003).

Si la ideología es un conjunto de actitudes, valores y creencias, junto con motivaciones existenciales, epistémicas y relacionales, puede ser separada por su contenido discursivo y por su función, en cuanto las necesidades psicológicas y sociales que satisface. La relación entre contenido ideológico y función psicológica, se ordenaría como un proceso de afinidad lectiva, en donde los discursos ideológicos son seleccionados y reinterpretados en base a las motivaciones psicológicas de los individuos (Jost, Federico, & Napier, 2009).

La literatura advierte que existe una relación entre la percepción del miedo como motivación existencial y el conservadurismo político de derecha (Jost, Stern, Rule, & Sterling, 2017). Una serie de estudios relacionan el apoyo a actitudes conservadoras con necesidades epistémicas y relacionales como la percepción de miedo, amenaza, intolerancia a la ambigüedad, evitar la incertidumbre y la necesidad de orden (Thórisdóttir & Jost, 2011).

La influencia del miedo sobre otros fenómenos ha sido ampliamente estudiado en el ámbito de la criminología. Algunos autores (Vozmediano, San Juan , & Vergara, 2008), sugieren separar la percepción subjetiva de los individuos de los índices objetivos de seguridad y delito. Esto implica entender el miedo a la delincuencia más allá de una perspectiva criminológica, como parte de una temática mayor de la percepción de inseguridad (Muratori & Zubieta, 2013), que incluye no solo la delincuencia tradicional sino también el vandalismo, el terrorismo, u otras amenazas, en las que se puede incluir las protestas sociales.

Así también, el rol de las emociones en las percepciones sociales ha sido ampliamente estudiado desde la sociología. Diversos autores hablan de un giro afectivo, buscando vincular las emociones humanas con los problemas fundamentales de la sociología (Martell & Caro, 2023). Aunque las emociones actúan en diversos planos de la realidad relacionados entre sí, estudiar este fenómeno desde la sociología implica delimitar cual es el componente propiamente social de estas. Aún cuando se entienden las emociones como un fenómeno relacional entre cultura y biología, la sociología ha optado por una salida constructivista en cuanto las emociones son objetos cognocibles en la medida en que estas se comunican (Bericat, 2000).

Hay poca evidencia respecto a como las emociones moldean las justificaciones de la violencia, no obstante, una de las áreas temáticas de la sociología de las emociones ha sido la conexión entre movilizaciones sociales y sentimientos (Ariza, 2021). En este sentido, se ha resaltado el rol del miedo como emoción social, en cuanto representa la fragilización de los vínculos sociales. Así también, en una situación de protesta social, diversas percepciones y actitudes pueden verse afectadas por emociones específicas relacionadas al contexto y los actores involucrados (Jasper, 1998).

Desarrollos teóricos posteriores han resaltado la relevancia de las emociones que experimentan los individuos en relación a un grupo social. En ellas, el rol crítico de las emociones reside en el reconocimiento de la identidad del sujeto en su relación con el grupo y la evaluación que se realice del contexto. En este caso, la dimensión social de las emociones reside en que, bajo ciertas características, las personas pueden conectar entre sí incluso si son observadores de una acción que es perpetrada por una tercera persona (Yzerbyt, Dumont, Wigboldus, & Gordijn, 2003).

La teoría de las emociones intergrupales, destaca el rol de estas en la regulación de las percepciones y la conducta de los individuos, incluyendo las relaciones intra e intergrupales (Mackie, Devos, & Smith, 2000). En ellas, el rol crítico de las emociones reside en el reconocimiento de la identidad del sujeto en su relación con el grupo y la evaluación que se realice del contexto (Yzerbyt, Dumont, Wigboldus, & Gordijn, 2003). Así, las emociones se vinculan a distintos fenómenos relacionado con las percepciones sociales, entendidas estas como aquellos esquemas de conocimiento compartido acerca de la realidad social que orienta la conducta de las personas de un grupo social. La premisa de esta teoría resalta el aspecto cognitivo, en donde las respuestas emocionales diferenciadas frente al mismo estímulo obedecen a mecanismos de cognición diferenciados (Smith, Seger, & Mackie, 2007).

Aunque el tratamiento de las emociones desde las perspectivas de la afinidad lectiva (Jost, Federico, & Napier, 2009) y de las emociones intergrupales (Smith, Seger, & Mackie, 2007) incurren en cierto esencialismo psicológico (Estrada, Oyarzún , & Yzerbyt, 2007), en la medida en que se destacan las formas de percepción individual en las representaciones sociales, estos argumentos pueden ser extendido más allá de este plano, destacando el aspecto social o intergrupal de las emociones y sus efectos en las percepciones de los individuos.

En este sentido, puede vincularse las emociones a distintos fenómenos relacionado con las percepciones sociales, entendido como aquellos esquemas de conocimiento compartido acerca de la realidad social que orienta la conducta de las personas de un grupo social: ¿hasta qué punto el miedo tiene un efecto directo o indirecto en las relaciones intergrupales?, ¿cómo se relacionan las emociones con categorizaciones racionales como la orientación política? Aunque ambos conceptos funcionan en planos distintos, son comparables en cuanto poseen cargas motivacionales que incitan a formas diferenciadas de acción.

El razonamiento argumentativo de esta investigación parte desde el siguiente planteamiento: el clima socio-emocional post-estallido, marcado por una crisis de inseguridad, puede generar percepciones diferenciadas hacia la protesta social según orientación política. En este marco, el rol de las emociones en las percepciones intergrupales puede cobrar mayor relevancia en la justificación de la violencia en contexto de protesta. Así, proponemos que el miedo a los actores relacionados a la protesta social actúa como variable moderadora (Ato & Vallejo, 2010), alterando la magnitud de la relación entre la orientación política y la justificación de la violencia en contexto de protesta.

Por un lado, el miedo a manifestantes y la orientación política de derecha, pueden interactuar aumentando los chances de que los individuos justifiquen la violencia policial, bajo el razonamiento de que las manifestaciones representan una amenaza contra el orden público, la estabilidad y el orden social (Rottenbacher de Rojas & Schmitz, 2013). Así también, el miedo a Carabineros y la orientación política de izquierda pueden interactuar aumentando los chances de que los individuos justifiquen la violencia de manifestantes, considerando que las emociones negativas hacia Carabineros tienen un efecto mayor sobre quienes son más proclives a justificar el cambio social.
:::
