::: {style="text-align: justify"}

## 3. Pregunta de investigación

**Pregunta**: ¿Cómo se relaciona la orientación política con el miedo a los actores relacionados a la protesta social en la justificación de la violencia en contexto de protesta en Chile el año 2022?

**Objetivo general**: Analizar la relación de la orientación política y el miedo a los actores relacionados a la protesta social con la justificación de la violencia en contexto de protesta en Chile el año 2022.

**Objetivos específicos**:

1. Determinar la relación entre orientación política y justificación de la violencia de Carabineros y manifestantes.

2. Determinar la relación entre miedo a Carabineros con la justificación de manifestantes.

3. Determinar la relación entre miedo a manifestantes con la justificación de la violencia de Carabineros.

4. Describir la relación entre miedo a Carabineros y orientación política.

5. Describir la relación entre miedo a manifestantes y orientación política.

6. Determinar la interacción entre miedo a manifestantes y orientación política de derecha sobre la justificación de la violencia de Carabineros.

7. Determinar la interacción entre miedo a Carabineros y orientación política de izquierda sobre la justificación de la violencia de manifestantes.

:::
